# .github/workflows/deploy.yml

name: Build and Push Container Images to ACR

# This workflow runs on any push to the 'main' branch
on:
  push:
    branches: [ main ]

# Permissions are required for the OIDC token exchange
permissions:
  id-token: write
  contents: read

# --- IMPORTANT: UPDATE THESE VALUES ---
env:
  ACR_NAME: "etlonline"
  FRONTEND_IMAGE_NAME: "prompt-competition-2025-frontend"
  BACKEND_IMAGE_NAME: "prompt-competition-2025-backend"
# ------------------------------------

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Azure with OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.ACR_NAME }}.azurecr.io

    - name: Build and push frontend image to ACR
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.frontend
        push: true
        tags: |
          ${{ env.ACR_NAME }}.azurecr.io/${{ env.FRONTEND_IMAGE_NAME }}:${{ github.sha }}
          ${{ env.ACR_NAME }}.azurecr.io/${{ env.FRONTEND_IMAGE_NAME }}:latest

    - name: Build and push backend image to ACR
      uses: docker/build-push-action@v5
      with:
        context: ./server
        file: ./Dockerfile.backend
        push: true
        tags: |
          ${{ env.ACR_NAME }}.azurecr.io/${{ env.BACKEND_IMAGE_NAME }}:${{ github.sha }}
          ${{ env.ACR_NAME }}.azurecr.io/${{ env.BACKEND_IMAGE_NAME }}:latest

# End of workflow. The deployment steps have been removed.
